name: "Build and deploy"
on:
  push:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
  
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for force deployment?"
        required: true
        default: 'Test run'
        type: string

concurrency:
  group: "udacity"
  cancel-in-progress: true
  
permissions:
  contents: read
  pages: write
  issues: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      url_checker_timeout: ${{ vars.URL_CHECKER_TIMEOUT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=18'
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.workflow }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |  # Added restore key to make the cache search process faster if the key is not found.
            ${{ runner.os }}-node-${{ github.workflow }}-
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      
      - name: Run all the linters
        run: npm run lint:all

      # Run all the additional scripts that are required
      - name: Run all the scripts
        run: |
          node script/url-checker.js -t $url_checker_timeout

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=18"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.workflow }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | # Added restore key to make the cache search process faster if the key is not found.
            ${{ runner.os }}-node-${{ github.workflow }}-
            ${{ runner.os }}-node-
            
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build distribution files
        run: |
          PATH_PREFIX = ${{ vars.PATH_PREFIX }}
          npm run prod

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"
  
  deploy:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages  # Reference : https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#deploying-github-pages-artifacts
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Report status
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
          TODAY=$(date '+%Y-%m-%d %I:%M:%S %p')
          # Create a new issue with the deployment status
          gh issue create \
            --repo ${{ github.repository }} \
            --title "Deployment: ${{ steps.deployment.outcome }} on $TODAY" \
            --body "URL of Deployed site: $url"
